const C=window.CBE||{};
const nav=document.querySelector('#nav'),toggle=document.querySelector('.menu-toggle');
const closeDrops=()=>document.querySelectorAll('.nav-group.open').forEach(g=>{g.classList.remove('open');g.querySelector('.nav-drop')?.setAttribute('aria-expanded','false')});
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));if(!open)closeDrops()});
document.querySelectorAll('.nav-drop').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const g=b.closest('.nav-group'),was=g.classList.contains('open');closeDrops();g.classList.toggle('open',!was);b.setAttribute('aria-expanded',String(!was))}));
document.addEventListener('click',e=>{if(!e.target.closest('.nav-group'))closeDrops()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrops()});
window.addEventListener('scroll',()=>{closeDrops();nav?.classList.remove('open');toggle?.setAttribute('aria-expanded','false')},{passive:true});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{closeDrops();nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('#year').forEach(el=>el.textContent=String(new Date().getFullYear()));
document.querySelectorAll('[data-link]').forEach(a=>{const url=C[a.dataset.link];if(url)a.href=url;else{a.removeAttribute('href');a.classList.add('unconfigured')}});
const video=document.querySelector('#latest-video');
const ytChannel=C.youtube||'https://www.youtube.com/@CertifiedBadExample_Podcast';
const latestCache='cbe:lastVerifiedLongform:v08';
function showVideo(item){if(!video||!item||!/^[-_a-zA-Z0-9]{11}$/.test(item.videoId))return false;const frame=document.createElement('iframe');frame.src=`https://www.youtube-nocookie.com/embed/${item.videoId}?playsinline=1`;frame.title=item.title||'Certified Bad Example long-form episode';frame.allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share';frame.allowFullscreen=true;frame.loading='lazy';video.replaceChildren(frame);const pop=document.querySelector('#latest-actions a');if(pop)pop.href=`https://www.youtube.com/watch?v=${item.videoId}`;return true}
function videoWaiting(){if(!video)return;video.innerHTML='';const wrap=document.createElement('div');wrap.className='video-placeholder';wrap.innerHTML='<strong>THE DRAMA IS LOADING. THE WAIT WILL BE WORTH IT.</strong><p>You came for the chaos, and we respect that. There’s plenty of questionable behavior to keep you entertained. Catch up on past episodes, subscribe, and stick around. Jameel and August always have something to say.</p><p class="video-tagline">GOOD THINGS COME TO THOSE WHO WAIT. BAD EXAMPLES COME WITH COMMENTARY.</p>';const a=document.createElement('a');a.href=ytChannel+'/videos';a.target='_blank';a.rel='noopener';a.className='button';a.textContent='WATCH PREVIOUS EPISODES ↗';wrap.append(a);video.append(wrap)}
async function loadLatest(){if(!video)return;let cached=null;try{cached=JSON.parse(localStorage.getItem(latestCache)||'null')}catch{}if(cached?.videoId)showVideo(cached);else if(C.latestYouTubeVideoId)showVideo({videoId:C.latestYouTubeVideoId});else videoWaiting();try{const response=await fetch('/api/latest',{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('YouTube unavailable');const data=await response.json();if(!/^[-_a-zA-Z0-9]{11}$/.test(data.videoId))throw Error('No verified long-form episode');showVideo(data);try{localStorage.setItem(latestCache,JSON.stringify(data))}catch{}}catch(e){/* Preserve last verified playable episode; otherwise show neutral message. */}}
loadLatest();
const track=document.querySelector('#episode-track'),picker=document.querySelector('#season-select'),status=document.querySelector('#episode-status'),marquee=document.querySelector('.marquee');let allEpisodes=[];const epCache='cbe:episodeArchive:v08';
const clean=s=>String(s||'').replace(/<[^>]*>/g,'').trim();
function renderEpisodes(season){if(!track)return;const episodes=allEpisodes.filter(x=>Number(x.season)===Number(season)).sort((a,b)=>Number(b.number)-Number(a.number));const cards=episodes.map(ep=>{const a=document.createElement('a');a.className='episode-card';a.href=ep.url||C.captivate;a.target='_blank';a.rel='noopener';const art=document.createElement('div');art.className='episode-art';if(ep.image){const img=document.createElement('img');img.src=ep.image;img.loading='lazy';img.alt='';img.onerror=()=>{img.remove();art.classList.add('no-art')};art.append(img)}else art.classList.add('no-art');const copy=document.createElement('div');copy.className='episode-copy';const kicker=document.createElement('small');kicker.textContent=`SEASON ${String(ep.season).padStart(2,'0')} · EPISODE ${String(ep.number).padStart(2,'0')}`;const title=document.createElement('strong');title.textContent=clean(ep.title);const desc=document.createElement('p');desc.textContent=clean(ep.description).slice(0,155);copy.append(kicker,title,desc);a.append(art,copy);return a});track.replaceChildren(...cards);if(status)status.textContent=episodes.length?`Season ${season} · ${episodes.length} published episodes.`:'';if(marquee)marquee.scrollLeft=0}
function useEpisodes(episodes){if(!Array.isArray(episodes)||!episodes.length)return;allEpisodes=episodes;const seasons=[...new Set(episodes.map(e=>Number(e.season)).filter(Boolean))].sort((a,b)=>b-a);if(picker){picker.replaceChildren(...seasons.map(s=>{const o=document.createElement('option');o.value=s;o.textContent=`Season ${s}`;return o}));const requested=Number(new URLSearchParams(location.search).get('season'));picker.value=String(seasons.includes(requested)?requested:seasons[0]);renderEpisodes(picker.value)}const sub=document.querySelector('#season-nav');if(sub){sub.replaceChildren();const overview=document.createElement('a');overview.href='index.html#stories';overview.textContent='Browse episodes';sub.append(overview);seasons.forEach(season=>{const a=document.createElement('a');a.href=`index.html?season=${season}#stories`;a.textContent=`Season ${season}`;sub.append(a)})}}
async function loadEpisodes(){if(!track)return;try{const saved=JSON.parse(localStorage.getItem(epCache)||'null');if(saved?.length)useEpisodes(saved)}catch{}try{const r=await fetch('/api/episodes',{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Archive unavailable');const data=await r.json();if(!data.episodes?.length)throw Error('Empty archive');useEpisodes(data.episodes);try{localStorage.setItem(epCache,JSON.stringify(data.episodes))}catch{}}catch(e){/* Preserve cached cards, no fallback message by request. */}if(status&& !allEpisodes.length)status.textContent=''}
picker?.addEventListener('change',()=>renderEpisodes(picker.value));
document.querySelector('#episode-prev')?.addEventListener('click',()=>marquee?.scrollBy({left:-520,behavior:'smooth'}));
document.querySelector('#episode-next')?.addEventListener('click',()=>marquee?.scrollBy({left:520,behavior:'smooth'}));
loadEpisodes();
const support=document.querySelector('#support-links');if(support&&C.captivateDonation){const a=document.createElement('a');a.className='button';a.textContent='SUPPORT VIA CAPTIVATE ↗';a.href=C.captivateDonation;a.target='_blank';a.rel='noopener';support.append(a)}
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('in-view'));

