const C=window.CBE||{};
const nav=document.querySelector('#nav'),toggle=document.querySelector('.menu-toggle');
const closeDrops=()=>document.querySelectorAll('.nav-group.open').forEach(g=>{g.classList.remove('open');g.querySelector('.nav-drop')?.setAttribute('aria-expanded','false')});
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));if(!open)closeDrops()});
document.querySelectorAll('.nav-drop').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const g=b.closest('.nav-group'),was=g.classList.contains('open');closeDrops();g.classList.toggle('open',!was);b.setAttribute('aria-expanded',String(!was))}));
document.addEventListener('click',e=>{if(!e.target.closest('.nav-group'))closeDrops()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrops()});
window.addEventListener('scroll',()=>{closeDrops();nav?.classList.remove('open');toggle?.setAttribute('aria-expanded','false')},{passive:true});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{closeDrops();nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('#year').forEach(el=>el.textContent=String(new Date().getFullYear()));
document.querySelectorAll('[data-link]').forEach(a=>{const url=C[a.dataset.link];if(url)a.href=url;else{a.removeAttribute('href');a.classList.add('unconfigured')}});
const video=document.querySelector('#latest-video');
async function loadLatest(){if(!video)return;try{const r=await fetch('/api/latest',{signal:AbortSignal.timeout(11000)});if(!r.ok)throw Error('Feed unavailable');const data=await r.json();if(!/^[\w-]{11}$/.test(data.videoId))throw Error('No latest video');const f=document.createElement('iframe');f.src=`https://www.youtube-nocookie.com/embed/${data.videoId}`;f.title=data.title||'Latest Certified Bad Example episode';f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';f.allowFullscreen=true;f.loading='lazy';video.replaceChildren(f)}catch(e){video.querySelector('strong').textContent='WATCH THE LATEST MESS ON YOUTUBE';}}
loadLatest();
const track=document.querySelector('#episode-track'),picker=document.querySelector('#season-select'),status=document.querySelector('#episode-status');let allEpisodes=[];
const clean=s=>String(s||'').replace(/<[^>]*>/g,'').trim();
function renderEpisodes(season){if(!track)return;track.replaceChildren();const episodes=allEpisodes.filter(x=>Number(x.season)===Number(season)).sort((a,b)=>Number(b.number)-Number(a.number));if(!episodes.length){status.textContent='No published episodes found for this season. Explore the podcast archive on Captivate.';return}status.textContent=`Season ${season} · ${episodes.length} published episodes. Select a card to listen.`;
const card=(ep,clone=false)=>{const a=document.createElement('a');a.className='episode-card';a.href=ep.url||C.captivate;a.target='_blank';a.rel='noopener';if(clone){a.setAttribute('aria-hidden','true');a.tabIndex=-1;}const img=document.createElement('div');img.className='episode-art';if(ep.image){const im=document.createElement('img');im.src=ep.image;im.loading='lazy';im.alt='';img.append(im)}else img.classList.add('no-art');const content=document.createElement('div');content.className='episode-copy';const kicker=document.createElement('small');kicker.textContent=`SEASON ${String(ep.season).padStart(2,'0')} · EPISODE ${String(ep.number).padStart(2,'0')}`;const title=document.createElement('strong');title.textContent=clean(ep.title);const desc=document.createElement('p');desc.textContent=clean(ep.description).slice(0,155);content.append(kicker,title,desc);a.append(img,content);return a};episodes.forEach(ep=>track.append(card(ep)));if(episodes.length>1)episodes.forEach(ep=>track.append(card(ep,true)));track.classList.toggle('no-motion',episodes.length<2);}
async function loadEpisodes(){if(!track)return;try{const r=await fetch('/api/episodes',{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Feed unavailable');const d=await r.json();allEpisodes=d.episodes||[];if(!allEpisodes.length)throw Error('No episodes');const seasons=[...new Set(allEpisodes.map(e=>Number(e.season)).filter(Boolean))].sort((a,b)=>b-a);picker.replaceChildren(...seasons.map(s=>{const o=document.createElement('option');o.value=s;o.textContent=`Season ${s}`;return o}));const requested=Number(new URLSearchParams(location.search).get('season'));picker.value=seasons.includes(requested)?String(requested):String(seasons[0]);renderEpisodes(picker.value);const sub=document.querySelector('#season-nav');if(sub){sub.replaceChildren();const overview=document.createElement('a');overview.href='index.html#stories';overview.textContent='Browse episodes';sub.append(overview);seasons.forEach(s=>{const a=document.createElement('a');a.href=`index.html?season=${s}#stories`;a.textContent=`Season ${s}`;sub.append(a)})}}catch(e){status.innerHTML='Episode catalog temporarily unavailable. <a class="back" href="'+C.captivate+'" target="_blank" rel="noopener">Browse all episodes on Captivate ↗</a>';track.replaceChildren()}}
picker?.addEventListener('change',()=>renderEpisodes(picker.value));loadEpisodes();
const support=document.querySelector('#support-links');if(support&&C.captivateDonation){const a=document.createElement('a');a.className='button';a.textContent='SUPPORT VIA CAPTIVATE ↗';a.href=C.captivateDonation;a.target='_blank';a.rel='noopener';support.append(a)}
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('in-view'));
const form=document.querySelector('#story-form');form?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),body=[...d.entries()].map(([k,v])=>`${k}: ${v}`).join('\n\n');location.href=`mailto:${C.submissionEmail}?subject=${encodeURIComponent('CBE Story Submission: '+d.get('Story headline'))}&body=${encodeURIComponent(body)}`;document.querySelector('#form-status').textContent='Your email app should open with a prepared submission. Press Send to complete it.'});
